### ISSUE TITLE
Allow removal of first dog

### ISSUE THREAD

**Issue by finneganh** [CityOfBoston/cityofboston.gov#1]
Go to: https://www.cityofboston.gov/animals/licenseapp/# 

Enter sample dog information [see Reilly for this] and click the bottom to go through the process

Once you get to 'step 2 - dog information'
 
Once you get to Step 2: All dogs that are entered in 2nd or 3rd or greater dog, a user can select 'not applicable' which allows the user to get rid of an animal and let's the user proceed with the application. 
 
This is not allowed on first dog and cause tremendous user confusion [many users are starting online and having to call/come in]. 
 
We need to add 'not applicable' to first dog to mimic the functionality on dog two+.

**Comment by finneganh** [comment]
@reillyzlab I think this is fixed? Maybe someone at Animal Control can test it out?

**Comment by reillyzlab** [comment]
Notified Animal Care and Control that is it fixed and asked them to confirm that it's 100% working as they expect.
