### ISSUE TITLE
City Council Migration

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/cityofboston.gov#16]
This is related the cable office but is linked from the City Council page 

1. City Council Video Library: 
https://www.cityofboston.gov/citycouncil/cc_video_library.asp

Boston.gov Links: https://www.boston.gov/departments/city-council/watch-boston-city-council-tv#city-council-tv-video-library

City Council> Get Started> Watch a City Council Hearing> Search through our video archives link

2. View City Charter
https://www.cityofboston.gov/Images_Documents/Boston%20City%20Charter_tcm3-18855.pdf

Boston.gov Link: https://www.boston.gov/departments/city-council/how-city-council-enacts-laws

City Council> Get Started> How the City Council Enacts laws > View the City Charter Link

**Comment by duffy-james** [comment]
@stephaniemar the City Charter piece of this is all set. I think you can close this out. This is really related to the [Cable Office Migration](https://github.com/CityOfBoston/cityofboston.gov/issues/15).
